spring:
  application:
    name: auctions-system
  datasource:
    url: jdbc:postgresql://localhost:5432/auctions_system
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

jwt:
  #  secret: ${JWT_SECRET:dev-secret-key-must-be-at-least-32-chars!!}
  secret: dev-secret-key
  access-expiration-ms: 86400000    # 24 horas
  refresh-expiration-ms: 604800000  # 7 días
