services:
  postgres:
    image: postgres:16-alpine
    container_name: auctions-postgres
    environment:
      POSTGRES_DB: auctions_system
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - auctions_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d auctions_system"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  auctions_postgres_data:
    driver: local
