package domain.outbox;

public enum EventType {
  BID_PLACED,
  BID_OUTBID,
  BID_CANCELLED,
  AUCTION_PUBLISHED,
  AUCTION_ACTIVATED,
  AUCTION_CANCELLED,
  AUCTION_AWARDED,
  AUCTION_FAILED,
  USER_REGISTERED,
  WALLET_DEPOSITED,
  WALLET_WITHDRAWN
}
